steps:
  - name: 'gcr.io/cloud-builders/npm'
    args: ['install']
    dir: 'saas-platform/frontend'
  - name: 'gcr.io/cloud-builders/npm'
    args: ['run', 'build']
    dir: 'saas-platform/frontend'
